wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/src/run.py
    python_version: 3.10.7
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700468471.606336
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.10.7
      5: 0.16.0
      8:
      - 5
      13: darwin-x86_64
