wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/src/robot_run.py
    python_version: 3.9.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711668055.495405
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.9.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
