wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/src/run.py
    python_version: 3.9.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700679045.067114
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.9.13
      5: 0.16.0
      6: 4.32.0
      8:
      - 5
      13: linux-x86_64
